In [73]:
# HW10 - Ensemble Method

import pandas as pd
import numpy as np


In [74]:
# Read Input data
df=pd.read_csv("HW10_Ensemble.csv")

df.head(5)
df.count()


TrackID    120000
Pred_39    120000
Pred_18    120000
RF_HW9     120000
DT_HW9     120000
GBT_HW9    120000
dtype: int64

In [75]:
del df[df.columns[0]]
print(df)

        Pred_39  Pred_18  RF_HW9  DT_HW9  GBT_HW9
0             1        1       1       1        1
1             1        1       1       1        1
2             1       -1      -1      -1       -1
3            -1       -1      -1      -1       -1
4            -1       -1      -1      -1       -1
...         ...      ...     ...     ...      ...
119995        1        1       1       1        1
119996        1        1       1       1        1
119997       -1       -1      -1      -1       -1
119998       -1       -1      -1      -1       -1
119999       -1       -1      -1      -1       -1

[120000 rows x 5 columns]


In [77]:
S= df.values

S1=np.array([df["Pred_39"]]).T

print(S1)

[[ 1]
 [ 1]
 [ 1]
 ...
 [-1]
 [-1]
 [-1]]


In [78]:
# Transpose matrix
S_T=S.T

print(S_T)



[[ 1  1  1 ... -1 -1 -1]
 [ 1  1 -1 ... -1 -1 -1]
 [ 1  1 -1 ... -1 -1 -1]
 [ 1  1 -1 ... -1 -1 -1]
 [ 1  1 -1 ... -1 -1 -1]]


In [86]:
SS=np.dot(S_T,S)

In [89]:
p1=0.885*120000
p2=0.854*120000
p3=0.730*120000
p4=0.752*120000
p5=0.802*120000

In [90]:
B = np.array([[p1,p2,p3,p4,p5]]).T
print(B)

[[106200.]
 [102480.]
 [ 87600.]
 [ 90240.]
 [ 96240.]]


In [91]:
AV=np.linalg.inv(SS)

ALS=np.dot(AV,B)

print(ALS)

[[0.41635004]
 [0.26441146]
 [0.22263375]
 [0.16434786]
 [0.07905726]]


In [92]:
ensemble=np.dot(S,ALS)
print(ensemble)

[[ 1.14680037]
 [ 1.14680037]
 [-0.31410028]
 ...
 [-1.14680037]
 [-1.14680037]
 [-1.14680037]]


In [93]:
lst=(list(ensemble))

In [85]:
from pandas import DataFrame
df = DataFrame({'Ensemble': (lst)})
df
df.to_excel('ensemble3.xlsx', sheet_name='sheet1', index=False)